
name: Publish Docker image - php7-apache-base

on:
  push:
    branches: master
  paths:
    - 'php7-apache-base/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      #-
        #name: Set up QEMU
        #uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build php base image
        uses: docker/build-push-action@v2
        with:
          context: ./php7-apache-base
          file: ./php7-apache-base/Dockerfile
          push: true
          tags: raffaelj/php7-apache-base:latest
