
name: Publish Docker image - just a test

on:
  push:
    branches: master
  paths:
    - 'just-a-test/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      #-
        #name: Set up QEMU
        #uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build just-a-test
        uses: docker/build-push-action@v2
        with:
          context: ./just-a-test
          file: ./just-a-test/Dockerfile
          push: true
          tags: raffaelj/just-a-test:latest
